# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Code\Fun\Wai-

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Code\Fun\Wai-

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"D:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\Fun\Wai-\CMakeFiles D:\Code\Fun\Wai-\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Code\Fun\Wai-\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WAI_

# Build rule for target.
WAI_: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 WAI_
.PHONY : WAI_

# fast build rule for target.
WAI_/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/build
.PHONY : WAI_/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/AST/AST.obj: src/AST/AST.cpp.obj
.PHONY : src/AST/AST.obj

# target to build an object file
src/AST/AST.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/AST.cpp.obj
.PHONY : src/AST/AST.cpp.obj

src/AST/AST.i: src/AST/AST.cpp.i
.PHONY : src/AST/AST.i

# target to preprocess a source file
src/AST/AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/AST.cpp.i
.PHONY : src/AST/AST.cpp.i

src/AST/AST.s: src/AST/AST.cpp.s
.PHONY : src/AST/AST.s

# target to generate assembly for a file
src/AST/AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/AST.cpp.s
.PHONY : src/AST/AST.cpp.s

src/AST/Node/ASTNode.obj: src/AST/Node/ASTNode.cpp.obj
.PHONY : src/AST/Node/ASTNode.obj

# target to build an object file
src/AST/Node/ASTNode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/ASTNode.cpp.obj
.PHONY : src/AST/Node/ASTNode.cpp.obj

src/AST/Node/ASTNode.i: src/AST/Node/ASTNode.cpp.i
.PHONY : src/AST/Node/ASTNode.i

# target to preprocess a source file
src/AST/Node/ASTNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/ASTNode.cpp.i
.PHONY : src/AST/Node/ASTNode.cpp.i

src/AST/Node/ASTNode.s: src/AST/Node/ASTNode.cpp.s
.PHONY : src/AST/Node/ASTNode.s

# target to generate assembly for a file
src/AST/Node/ASTNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/ASTNode.cpp.s
.PHONY : src/AST/Node/ASTNode.cpp.s

src/AST/Node/Number/NumberNode.obj: src/AST/Node/Number/NumberNode.cpp.obj
.PHONY : src/AST/Node/Number/NumberNode.obj

# target to build an object file
src/AST/Node/Number/NumberNode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Number/NumberNode.cpp.obj
.PHONY : src/AST/Node/Number/NumberNode.cpp.obj

src/AST/Node/Number/NumberNode.i: src/AST/Node/Number/NumberNode.cpp.i
.PHONY : src/AST/Node/Number/NumberNode.i

# target to preprocess a source file
src/AST/Node/Number/NumberNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Number/NumberNode.cpp.i
.PHONY : src/AST/Node/Number/NumberNode.cpp.i

src/AST/Node/Number/NumberNode.s: src/AST/Node/Number/NumberNode.cpp.s
.PHONY : src/AST/Node/Number/NumberNode.s

# target to generate assembly for a file
src/AST/Node/Number/NumberNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Number/NumberNode.cpp.s
.PHONY : src/AST/Node/Number/NumberNode.cpp.s

src/AST/Node/Operator/Addition/AdditionNode.obj: src/AST/Node/Operator/Addition/AdditionNode.cpp.obj
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.obj

# target to build an object file
src/AST/Node/Operator/Addition/AdditionNode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Addition/AdditionNode.cpp.obj
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.cpp.obj

src/AST/Node/Operator/Addition/AdditionNode.i: src/AST/Node/Operator/Addition/AdditionNode.cpp.i
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.i

# target to preprocess a source file
src/AST/Node/Operator/Addition/AdditionNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Addition/AdditionNode.cpp.i
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.cpp.i

src/AST/Node/Operator/Addition/AdditionNode.s: src/AST/Node/Operator/Addition/AdditionNode.cpp.s
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.s

# target to generate assembly for a file
src/AST/Node/Operator/Addition/AdditionNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Addition/AdditionNode.cpp.s
.PHONY : src/AST/Node/Operator/Addition/AdditionNode.cpp.s

src/AST/Node/Operator/Multiplication/MultiplicationNode.obj: src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.obj
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.obj

# target to build an object file
src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.obj
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.obj

src/AST/Node/Operator/Multiplication/MultiplicationNode.i: src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.i
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.i

# target to preprocess a source file
src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.i
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.i

src/AST/Node/Operator/Multiplication/MultiplicationNode.s: src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.s
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.s

# target to generate assembly for a file
src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.s
.PHONY : src/AST/Node/Operator/Multiplication/MultiplicationNode.cpp.s

src/Logger/Logger.obj: src/Logger/Logger.cpp.obj
.PHONY : src/Logger/Logger.obj

# target to build an object file
src/Logger/Logger.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Logger/Logger.cpp.obj
.PHONY : src/Logger/Logger.cpp.obj

src/Logger/Logger.i: src/Logger/Logger.cpp.i
.PHONY : src/Logger/Logger.i

# target to preprocess a source file
src/Logger/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Logger/Logger.cpp.i
.PHONY : src/Logger/Logger.cpp.i

src/Logger/Logger.s: src/Logger/Logger.cpp.s
.PHONY : src/Logger/Logger.s

# target to generate assembly for a file
src/Logger/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Logger/Logger.cpp.s
.PHONY : src/Logger/Logger.cpp.s

src/Parser/Parser.obj: src/Parser/Parser.cpp.obj
.PHONY : src/Parser/Parser.obj

# target to build an object file
src/Parser/Parser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Parser/Parser.cpp.obj
.PHONY : src/Parser/Parser.cpp.obj

src/Parser/Parser.i: src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.i

# target to preprocess a source file
src/Parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Parser/Parser.cpp.i
.PHONY : src/Parser/Parser.cpp.i

src/Parser/Parser.s: src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.s

# target to generate assembly for a file
src/Parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Parser/Parser.cpp.s
.PHONY : src/Parser/Parser.cpp.s

src/Token/Token.obj: src/Token/Token.cpp.obj
.PHONY : src/Token/Token.obj

# target to build an object file
src/Token/Token.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Token/Token.cpp.obj
.PHONY : src/Token/Token.cpp.obj

src/Token/Token.i: src/Token/Token.cpp.i
.PHONY : src/Token/Token.i

# target to preprocess a source file
src/Token/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Token/Token.cpp.i
.PHONY : src/Token/Token.cpp.i

src/Token/Token.s: src/Token/Token.cpp.s
.PHONY : src/Token/Token.s

# target to generate assembly for a file
src/Token/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Token/Token.cpp.s
.PHONY : src/Token/Token.cpp.s

src/Utils/Utils.obj: src/Utils/Utils.cpp.obj
.PHONY : src/Utils/Utils.obj

# target to build an object file
src/Utils/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Utils/Utils.cpp.obj
.PHONY : src/Utils/Utils.cpp.obj

src/Utils/Utils.i: src/Utils/Utils.cpp.i
.PHONY : src/Utils/Utils.i

# target to preprocess a source file
src/Utils/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Utils/Utils.cpp.i
.PHONY : src/Utils/Utils.cpp.i

src/Utils/Utils.s: src/Utils/Utils.cpp.s
.PHONY : src/Utils/Utils.s

# target to generate assembly for a file
src/Utils/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/Utils/Utils.cpp.s
.PHONY : src/Utils/Utils.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WAI_.dir\build.make CMakeFiles/WAI_.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... WAI_
	@echo ... cmake_pch.hxx.gch
	@echo ... cmake_pch.hxx.i
	@echo ... cmake_pch.hxx.s
	@echo ... src/AST/AST.obj
	@echo ... src/AST/AST.i
	@echo ... src/AST/AST.s
	@echo ... src/AST/Node/ASTNode.obj
	@echo ... src/AST/Node/ASTNode.i
	@echo ... src/AST/Node/ASTNode.s
	@echo ... src/AST/Node/Number/NumberNode.obj
	@echo ... src/AST/Node/Number/NumberNode.i
	@echo ... src/AST/Node/Number/NumberNode.s
	@echo ... src/AST/Node/Operator/Addition/AdditionNode.obj
	@echo ... src/AST/Node/Operator/Addition/AdditionNode.i
	@echo ... src/AST/Node/Operator/Addition/AdditionNode.s
	@echo ... src/AST/Node/Operator/Multiplication/MultiplicationNode.obj
	@echo ... src/AST/Node/Operator/Multiplication/MultiplicationNode.i
	@echo ... src/AST/Node/Operator/Multiplication/MultiplicationNode.s
	@echo ... src/Logger/Logger.obj
	@echo ... src/Logger/Logger.i
	@echo ... src/Logger/Logger.s
	@echo ... src/Parser/Parser.obj
	@echo ... src/Parser/Parser.i
	@echo ... src/Parser/Parser.s
	@echo ... src/Token/Token.obj
	@echo ... src/Token/Token.i
	@echo ... src/Token/Token.s
	@echo ... src/Utils/Utils.obj
	@echo ... src/Utils/Utils.i
	@echo ... src/Utils/Utils.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

